spring.datasource.url=jdbc:mysql://mysql:3306/financialnews?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
newsapi.base-url=https://newsapi.org/v2/everything
newsapi.api-key=${NEWS_API_KEY}